# Website's icon url.
favicon: /images/favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-dark
  # Date format: relative | full | relative_full | full_relative
  date_format: relative

# Navigation bar menu links.
menu:
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: false

# Share plugin settings.
#share:
#  type: sharethis
#  install_url:

# Comment plugin settings.
#comment:
#  type: disqus
#  shortname:
comment:
  type: giscus
  repo: fltb/blog-comments
  repo-id: R_kgDOJIHa8Q
  category: Announcements
  category-id: DIC_kwDOJIHa8c4CUzCw

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/fltb/

footer:
  enable_busuanzi: true
  enable_cc_license: true  # Toggle for CC license information
  license:
    name: "CC BY-NC-SA 4.0"  # License name to display
    url: "http://creativecommons.org/licenses/by-nc-sa/4.0/"  # Link to the license

float-monkey-patch-style:
  enable: true
  background-color: "#ebe7dc"